/**
 * API para Harbest
 * API para el backend del marketplace Harbest con MongoDB
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface LoginResponse { 
    /**
     * Token JWT para autenticación
     */
    token?: string;
    usuario?: User;
}

