/**
 * API para Harbest
 * API para el backend del marketplace Harbest con MongoDB
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Product { 
    readonly id?: string;
    nombre: string;
    precio: number;
    cantidad: number;
    descripcion: string;
    id_agricultor: string;
    foto: string;
}

