/**
 * API para Harbest
 * API para el backend del marketplace Harbest con MongoDB
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { Farmer } from '../model/farmer';
import { LoginDTO } from '../model/loginDTO';
import { LoginResponse } from '../model/loginResponse';
import { User } from '../model/user';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';


@Injectable()
export class AuthService {

    protected basePath = 'http://localhost:3000';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Inicio de Sesión de Agricultor
     * 
     * @param loginDTO 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [farmerLoginOpts.config] Override http request option.
     */
    public farmerLogin(loginDTO?: LoginDTO, farmerLoginOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<LoginResponse>>;
    public farmerLogin(loginDTO?: LoginDTO, farmerLoginOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<LoginResponse>(`${this.basePath}/auth/farmer/login`,
                    loginDTO,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...farmerLoginOpts?.config,
                        headers: {...headers, ...farmerLoginOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Registro de Agricultor
     * 
     * @param farmer 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [farmerRegisterOpts.config] Override http request option.
     */
    public farmerRegister(farmer?: Farmer, farmerRegisterOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<User>>;
    public farmerRegister(farmer?: Farmer, farmerRegisterOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<User>(`${this.basePath}/auth/farmer/register`,
                    farmer,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...farmerRegisterOpts?.config,
                        headers: {...headers, ...farmerRegisterOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Inicio de Sesión de Usuario
     * 
     * @param loginDTO 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [userLoginOpts.config] Override http request option.
     */
    public userLogin(loginDTO?: LoginDTO, userLoginOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<LoginResponse>>;
    public userLogin(loginDTO?: LoginDTO, userLoginOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<LoginResponse>(`${this.basePath}/auth/user/login`,
                    loginDTO,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...userLoginOpts?.config,
                        headers: {...headers, ...userLoginOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Registro de Usuario
     * 
     * @param user 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [userRegisterOpts.config] Override http request option.
     */
    public userRegister(user?: User, userRegisterOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<User>>;
    public userRegister(user?: User, userRegisterOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<User>(`${this.basePath}/auth/user/register`,
                    user,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...userRegisterOpts?.config,
                        headers: {...headers, ...userRegisterOpts?.config?.headers},
                    }
                );
            })
        );
    }
}
