/**
 * API para Harbest
 * API para el backend del marketplace Harbest con MongoDB
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { Product } from '../model/product';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';


@Injectable()
export class ProductService {

    protected basePath = 'http://localhost:3000';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Registrar un nuevo producto
     * 
     * @param product 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [createProductOpts.config] Override http request option.
     */
    public createProduct(product?: Product, createProductOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Product>>;
    public createProduct(product?: Product, createProductOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<Product>(`${this.basePath}/product`,
                    product,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...createProductOpts?.config,
                        headers: {...headers, ...createProductOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Obtener todos los productos
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [getProductsOpts.config] Override http request option.
     */
    public getProducts(getProductsOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<Product>>>;
    public getProducts(getProductsOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<Product>>(`${this.basePath}/products`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...getProductsOpts?.config,
                        headers: {...headers, ...getProductsOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Eliminar producto
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [productIdDeleteOpts.config] Override http request option.
     */
    public productIdDelete(id: string, productIdDeleteOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public productIdDelete(id: string, productIdDeleteOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling productIdDelete.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.delete<any>(`${this.basePath}/product/${encodeURIComponent(String(id))}`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...productIdDeleteOpts?.config,
                        headers: {...headers, ...productIdDeleteOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Obtener un producto por ID
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [productIdGetOpts.config] Override http request option.
     */
    public productIdGet(id: string, productIdGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Product>>;
    public productIdGet(id: string, productIdGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling productIdGet.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Product>(`${this.basePath}/product/${encodeURIComponent(String(id))}`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...productIdGetOpts?.config,
                        headers: {...headers, ...productIdGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Modificar producto
     * 
     * @param id 
     * @param product 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [productIdPutOpts.config] Override http request option.
     */
    public productIdPut(id: string, product?: Product, productIdPutOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public productIdPut(id: string, product?: Product, productIdPutOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling productIdPut.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.put<any>(`${this.basePath}/product/${encodeURIComponent(String(id))}`,
                    product,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...productIdPutOpts?.config,
                        headers: {...headers, ...productIdPutOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Obtener productos por ID de agricultor
     * 
     * @param idAgricultor 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [productsFarmerIdAgricultorGetOpts.config] Override http request option.
     */
    public productsFarmerIdAgricultorGet(idAgricultor: string, productsFarmerIdAgricultorGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<Product>>>;
    public productsFarmerIdAgricultorGet(idAgricultor: string, productsFarmerIdAgricultorGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (idAgricultor === null || idAgricultor === undefined) {
            throw new Error('Required parameter idAgricultor was null or undefined when calling productsFarmerIdAgricultorGet.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<Product>>(`${this.basePath}/products/farmer/${encodeURIComponent(String(idAgricultor))}`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...productsFarmerIdAgricultorGetOpts?.config,
                        headers: {...headers, ...productsFarmerIdAgricultorGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
}
